---
- name: Demo
  ansible.builtin.command: echo "DEMO"
  register: my_output # <- Registers the command output.
  changed_when: my_output.rc != 0 # <- Uses the return code to define when the task has changed.
