---
- name: user
  hosts: demo
  # any_errors_fatal: true
  # vars_prompt:
  #   - name: user
  #     prompt: "Введите пользователя"
  #     private: no
  #  vars_files:
  #   - ./my_vars.yml
  tasks:
    - name: Preconfig block
      become: true
      when: ansible_facts['distribution'] == 'Ubuntu' # Исполняеет таск если дистрибутив == UBUNTU
      block:
        - name: Create user
          vars:
            user: flat2
          user:
            name: "{{ user }}"
            state: present
          register: error
        - name: Install curl
          apt:
            name: curl
            update-cache: false
          register: error
      # - name: Fail on FAILED
      #   command: echo "FAILED"
      #   register: command_result
      #   failed_when: "'FAILED' in command_result.stdout"
      rescue:
        - name: Some error print
          debug:
            var: error
      always:
        - name: Reboot
          debug:
            msg: "Reboooting"
    #   register: out
    # - debug:
    #     var: out
      # debugger: always
