---
- name: "[{{ name }}] Создаем секрет"
  vars:
    config_file: "{{ lookup('template', '{{ name }}/.env.j2') }}"
  community.docker.docker_secret:
    name: "{{ name }}.env"
    data: "{{ config_file | b64encode }}"
    labels:
      config: "{{ config_file | hash('sha1') }}"
    data_is_b64: true
    state: present
