galaxy_info:
  role_name: swarm_init
  author: Anton Larichev
  description: Инициализация кластера swarm
  license: MIT
  min_ansible_version: "2.9"
  platforms:
    - name: Ubuntu
      versions:
        - all
