- name: Установка Docker
  become: true
  block:
    - name: Добавление репозиториев universe
      ansible.builtin.apt_repository:
        repo: "deb http://us.archive.ubuntu.com/ubuntu {{ ansible_distribution_release }} universe"
        state: present
    - name: Установка дополнительных пакетов
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
        update-cache: true
        cache_valid_time: 86400
    - name: Добавление ключа Docker
      ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /usr/share/keyrings/docker-archive-keyring.gpg
    - name: Установка стабильного репозитория
      ansible.builtin.apt_repository:
        repo: >
          deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg]
          https://download.docker.com/linux/ubuntu
          {{ ansible_distribution_release }} stable
        state: present
        update-cache: true
        filename: docker
    - name: Установка Docker-ce
      ansible.builtin.apt:
        name: docker-ce
        update-cache: true
    - name: Проверка что Docker установлен и перезагружен
      ansible.builtin.service:
        name: docker
        state: restarted
        enabled: true
- name: Установка Docker-compose
  become: true
  block:
    - name: Получение последней версии docker-compose
      ansible.builtin.uri:
        url: https://api.github.com/repos/docker/compose/releases/latest
        body_format: json
      register: page
    - name: Установка Docker-compose последней версии
      ansible.builtin.get_url:
        url: "https://github.com/docker/compose/releases/download/{{ page.json.tag_name }}/docker-compose-linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: 0755
- name: Настройка доп. пакетов python
  # become: true
  block:
    - name: Установка pip пакетов
      ansible.builtin.pip:
        name: docker
      register: page
- name: Завершение установки
  become: true
  block:
    - name: Добавление пользователя в группу Docker
      ansible.builtin.user:
        name: "{{ ansible_user }}"
        groups: docker
        append: true
    - name: Перезагрузка
      ansible.builtin.reboot:
